# -*- coding: utf-8 -*-
"""Proxys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9r25OFspujf186VIMl9kfXWIVVv1wcM
"""

import requests
import re

def get_my_ip(url="http://www.cualesmiip.com", proxies=None):
  try:
    r = requests.get(url=url, proxies=proxies)
  except Exception as e:
    print('Error haciendo la request', e)
    return None

  if r.status_code != 200:
    print('Status Code:', r.status_code)
    return None

  regex = re.compile(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})')
  my_ip = regex.findall(r.text)
  return my_ip[0] if my_ip else None

ip = get_my_ip()
print(ip)

proxy_dict = {'http': 'http://41.60.229.170:54169',
              'https' : 'https://41.60.229.170:54169'}
ip_with_proxy = get_my_ip(proxies=proxy_dict)
print(ip_with_proxy)

socks_proxy_dict = {'http': 'socks4://46.28.110.110:1080',
                    'https': 'socks4://46.28.110.110:1080'}
ip_with_socks = get_my_ip(proxies=socks_proxy_dict)
print(ip_with_socks)